apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
  labels:
    app: amazon-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amazon-app
  template:
    metadata:
      labels:
        app: amazon-app
    spec:
      containers:
        - name: amazon-container
          image: boboacr.azurecr.io/amazon_app:v1.0.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  selector:
    app: amazon-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
